/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsDriedFruitRouteImport } from './routes/products/dried-fruit'
import { Route as ProductsFreshApplesRouteImport } from './routes/products/fresh-apples'
import { Route as ProductsNutsRouteImport } from './routes/products/nuts'
import { Route as ProductsRooibosAndTeaRouteImport } from './routes/products/rooibos-and-tea'
import { Route as ServicesExportCoordinationRouteImport } from './routes/services/export-coordination'
import { Route as ServicesSupplierSourcingRouteImport } from './routes/services/supplier-sourcing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsDriedFruitRoute = ProductsDriedFruitRouteImport.update({
  id: '/products/dried-fruit',
  path: '/products/dried-fruit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFreshApplesRoute = ProductsFreshApplesRouteImport.update({
  id: '/products/fresh-apples',
  path: '/products/fresh-apples',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNutsRoute = ProductsNutsRouteImport.update({
  id: '/products/nuts',
  path: '/products/nuts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRooibosAndTeaRoute = ProductsRooibosAndTeaRouteImport.update({
  id: '/products/rooibos-and-tea',
  path: '/products/rooibos-and-tea',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExportCoordinationRoute =
  ServicesExportCoordinationRouteImport.update({
    id: '/services/export-coordination',
    path: '/services/export-coordination',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSupplierSourcingRoute =
  ServicesSupplierSourcingRouteImport.update({
    id: '/services/supplier-sourcing',
    path: '/services/supplier-sourcing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/dried-fruit': typeof ProductsDriedFruitRoute
  '/products/fresh-apples': typeof ProductsFreshApplesRoute
  '/products/nuts': typeof ProductsNutsRoute
  '/products/rooibos-and-tea': typeof ProductsRooibosAndTeaRoute
  '/services/export-coordination': typeof ServicesExportCoordinationRoute
  '/services/supplier-sourcing': typeof ServicesSupplierSourcingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/dried-fruit': typeof ProductsDriedFruitRoute
  '/products/fresh-apples': typeof ProductsFreshApplesRoute
  '/products/nuts': typeof ProductsNutsRoute
  '/products/rooibos-and-tea': typeof ProductsRooibosAndTeaRoute
  '/services/export-coordination': typeof ServicesExportCoordinationRoute
  '/services/supplier-sourcing': typeof ServicesSupplierSourcingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/products/dried-fruit': typeof ProductsDriedFruitRoute
  '/products/fresh-apples': typeof ProductsFreshApplesRoute
  '/products/nuts': typeof ProductsNutsRoute
  '/products/rooibos-and-tea': typeof ProductsRooibosAndTeaRoute
  '/services/export-coordination': typeof ServicesExportCoordinationRoute
  '/services/supplier-sourcing': typeof ServicesSupplierSourcingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/products/dried-fruit'
    | '/products/fresh-apples'
    | '/products/nuts'
    | '/products/rooibos-and-tea'
    | '/services/export-coordination'
    | '/services/supplier-sourcing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/products/dried-fruit'
    | '/products/fresh-apples'
    | '/products/nuts'
    | '/products/rooibos-and-tea'
    | '/services/export-coordination'
    | '/services/supplier-sourcing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/products/dried-fruit'
    | '/products/fresh-apples'
    | '/products/nuts'
    | '/products/rooibos-and-tea'
    | '/services/export-coordination'
    | '/services/supplier-sourcing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductsDriedFruitRoute: typeof ProductsDriedFruitRoute
  ProductsFreshApplesRoute: typeof ProductsFreshApplesRoute
  ProductsNutsRoute: typeof ProductsNutsRoute
  ProductsRooibosAndTeaRoute: typeof ProductsRooibosAndTeaRoute
  ServicesExportCoordinationRoute: typeof ServicesExportCoordinationRoute
  ServicesSupplierSourcingRoute: typeof ServicesSupplierSourcingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/dried-fruit': {
      id: '/products/dried-fruit'
      path: '/products/dried-fruit'
      fullPath: '/products/dried-fruit'
      preLoaderRoute: typeof ProductsDriedFruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fresh-apples': {
      id: '/products/fresh-apples'
      path: '/products/fresh-apples'
      fullPath: '/products/fresh-apples'
      preLoaderRoute: typeof ProductsFreshApplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/nuts': {
      id: '/products/nuts'
      path: '/products/nuts'
      fullPath: '/products/nuts'
      preLoaderRoute: typeof ProductsNutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/rooibos-and-tea': {
      id: '/products/rooibos-and-tea'
      path: '/products/rooibos-and-tea'
      fullPath: '/products/rooibos-and-tea'
      preLoaderRoute: typeof ProductsRooibosAndTeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/export-coordination': {
      id: '/services/export-coordination'
      path: '/services/export-coordination'
      fullPath: '/services/export-coordination'
      preLoaderRoute: typeof ServicesExportCoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/supplier-sourcing': {
      id: '/services/supplier-sourcing'
      path: '/services/supplier-sourcing'
      fullPath: '/services/supplier-sourcing'
      preLoaderRoute: typeof ServicesSupplierSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductsDriedFruitRoute: ProductsDriedFruitRoute,
  ProductsFreshApplesRoute: ProductsFreshApplesRoute,
  ProductsNutsRoute: ProductsNutsRoute,
  ProductsRooibosAndTeaRoute: ProductsRooibosAndTeaRoute,
  ServicesExportCoordinationRoute: ServicesExportCoordinationRoute,
  ServicesSupplierSourcingRoute: ServicesSupplierSourcingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
