/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GuidesDriedFruitBuyersGuideRouteImport } from './routes/guides/dried-fruit-buyers-guide'
import { Route as GuidesMacadamiaGradesGuideRouteImport } from './routes/guides/macadamia-grades-guide'
import { Route as GuidesRooibosTeaGuideRouteImport } from './routes/guides/rooibos-tea-guide'
import { Route as GuidesSouthAfricanAppleSeasonRouteImport } from './routes/guides/south-african-apple-season'
import { Route as GuidesSouthAfricanWineBuyersGuideRouteImport } from './routes/guides/south-african-wine-buyers-guide'
import { Route as ProductsDriedFruitRouteImport } from './routes/products/dried-fruit'
import { Route as ProductsFreshApplesRouteImport } from './routes/products/fresh-apples'
import { Route as ProductsNutsRouteImport } from './routes/products/nuts'
import { Route as ProductsRooibosAndTeaRouteImport } from './routes/products/rooibos-and-tea'
import { Route as ProductsWineRouteImport } from './routes/products/wine'
import { Route as ServicesExportCoordinationRouteImport } from './routes/services/export-coordination'
import { Route as ServicesSupplierSourcingRouteImport } from './routes/services/supplier-sourcing'
import { Route as SourcingDriedFruitAsiaRouteImport } from './routes/sourcing/dried-fruit/asia'
import { Route as SourcingDriedFruitGermanyRouteImport } from './routes/sourcing/dried-fruit/germany'
import { Route as SourcingDriedFruitUaeRouteImport } from './routes/sourcing/dried-fruit/uae'
import { Route as SourcingDriedFruitUnitedStatesRouteImport } from './routes/sourcing/dried-fruit/united-states'
import { Route as SourcingFreshApplesAsiaRouteImport } from './routes/sourcing/fresh-apples/asia'
import { Route as SourcingFreshApplesGermanyRouteImport } from './routes/sourcing/fresh-apples/germany'
import { Route as SourcingFreshApplesUaeRouteImport } from './routes/sourcing/fresh-apples/uae'
import { Route as SourcingFreshApplesUnitedStatesRouteImport } from './routes/sourcing/fresh-apples/united-states'
import { Route as SourcingMacadamiaNutsAsiaRouteImport } from './routes/sourcing/macadamia-nuts/asia'
import { Route as SourcingMacadamiaNutsGermanyRouteImport } from './routes/sourcing/macadamia-nuts/germany'
import { Route as SourcingMacadamiaNutsUaeRouteImport } from './routes/sourcing/macadamia-nuts/uae'
import { Route as SourcingMacadamiaNutsUnitedStatesRouteImport } from './routes/sourcing/macadamia-nuts/united-states'
import { Route as SourcingRooibosTeaAsiaRouteImport } from './routes/sourcing/rooibos-tea/asia'
import { Route as SourcingRooibosTeaGermanyRouteImport } from './routes/sourcing/rooibos-tea/germany'
import { Route as SourcingRooibosTeaUaeRouteImport } from './routes/sourcing/rooibos-tea/uae'
import { Route as SourcingRooibosTeaUnitedStatesRouteImport } from './routes/sourcing/rooibos-tea/united-states'
import { Route as SourcingWineAsiaRouteImport } from './routes/sourcing/wine/asia'
import { Route as SourcingWineGermanyRouteImport } from './routes/sourcing/wine/germany'
import { Route as SourcingWineUaeRouteImport } from './routes/sourcing/wine/uae'
import { Route as SourcingWineUnitedStatesRouteImport } from './routes/sourcing/wine/united-states'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDriedFruitBuyersGuideRoute =
  GuidesDriedFruitBuyersGuideRouteImport.update({
    id: '/guides/dried-fruit-buyers-guide',
    path: '/guides/dried-fruit-buyers-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesMacadamiaGradesGuideRoute =
  GuidesMacadamiaGradesGuideRouteImport.update({
    id: '/guides/macadamia-grades-guide',
    path: '/guides/macadamia-grades-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRooibosTeaGuideRoute = GuidesRooibosTeaGuideRouteImport.update({
  id: '/guides/rooibos-tea-guide',
  path: '/guides/rooibos-tea-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSouthAfricanAppleSeasonRoute =
  GuidesSouthAfricanAppleSeasonRouteImport.update({
    id: '/guides/south-african-apple-season',
    path: '/guides/south-african-apple-season',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSouthAfricanWineBuyersGuideRoute =
  GuidesSouthAfricanWineBuyersGuideRouteImport.update({
    id: '/guides/south-african-wine-buyers-guide',
    path: '/guides/south-african-wine-buyers-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsDriedFruitRoute = ProductsDriedFruitRouteImport.update({
  id: '/products/dried-fruit',
  path: '/products/dried-fruit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFreshApplesRoute = ProductsFreshApplesRouteImport.update({
  id: '/products/fresh-apples',
  path: '/products/fresh-apples',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNutsRoute = ProductsNutsRouteImport.update({
  id: '/products/nuts',
  path: '/products/nuts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRooibosAndTeaRoute = ProductsRooibosAndTeaRouteImport.update({
  id: '/products/rooibos-and-tea',
  path: '/products/rooibos-and-tea',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWineRoute = ProductsWineRouteImport.update({
  id: '/products/wine',
  path: '/products/wine',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesExportCoordinationRoute =
  ServicesExportCoordinationRouteImport.update({
    id: '/services/export-coordination',
    path: '/services/export-coordination',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSupplierSourcingRoute =
  ServicesSupplierSourcingRouteImport.update({
    id: '/services/supplier-sourcing',
    path: '/services/supplier-sourcing',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingDriedFruitAsiaRoute = SourcingDriedFruitAsiaRouteImport.update({
  id: '/sourcing/dried-fruit/asia',
  path: '/sourcing/dried-fruit/asia',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingDriedFruitGermanyRoute =
  SourcingDriedFruitGermanyRouteImport.update({
    id: '/sourcing/dried-fruit/germany',
    path: '/sourcing/dried-fruit/germany',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingDriedFruitUaeRoute = SourcingDriedFruitUaeRouteImport.update({
  id: '/sourcing/dried-fruit/uae',
  path: '/sourcing/dried-fruit/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingDriedFruitUnitedStatesRoute =
  SourcingDriedFruitUnitedStatesRouteImport.update({
    id: '/sourcing/dried-fruit/united-states',
    path: '/sourcing/dried-fruit/united-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingFreshApplesAsiaRoute = SourcingFreshApplesAsiaRouteImport.update({
  id: '/sourcing/fresh-apples/asia',
  path: '/sourcing/fresh-apples/asia',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingFreshApplesGermanyRoute =
  SourcingFreshApplesGermanyRouteImport.update({
    id: '/sourcing/fresh-apples/germany',
    path: '/sourcing/fresh-apples/germany',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingFreshApplesUaeRoute = SourcingFreshApplesUaeRouteImport.update({
  id: '/sourcing/fresh-apples/uae',
  path: '/sourcing/fresh-apples/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingFreshApplesUnitedStatesRoute =
  SourcingFreshApplesUnitedStatesRouteImport.update({
    id: '/sourcing/fresh-apples/united-states',
    path: '/sourcing/fresh-apples/united-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingMacadamiaNutsAsiaRoute =
  SourcingMacadamiaNutsAsiaRouteImport.update({
    id: '/sourcing/macadamia-nuts/asia',
    path: '/sourcing/macadamia-nuts/asia',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingMacadamiaNutsGermanyRoute =
  SourcingMacadamiaNutsGermanyRouteImport.update({
    id: '/sourcing/macadamia-nuts/germany',
    path: '/sourcing/macadamia-nuts/germany',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingMacadamiaNutsUaeRoute =
  SourcingMacadamiaNutsUaeRouteImport.update({
    id: '/sourcing/macadamia-nuts/uae',
    path: '/sourcing/macadamia-nuts/uae',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingMacadamiaNutsUnitedStatesRoute =
  SourcingMacadamiaNutsUnitedStatesRouteImport.update({
    id: '/sourcing/macadamia-nuts/united-states',
    path: '/sourcing/macadamia-nuts/united-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingRooibosTeaAsiaRoute = SourcingRooibosTeaAsiaRouteImport.update({
  id: '/sourcing/rooibos-tea/asia',
  path: '/sourcing/rooibos-tea/asia',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingRooibosTeaGermanyRoute =
  SourcingRooibosTeaGermanyRouteImport.update({
    id: '/sourcing/rooibos-tea/germany',
    path: '/sourcing/rooibos-tea/germany',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingRooibosTeaUaeRoute = SourcingRooibosTeaUaeRouteImport.update({
  id: '/sourcing/rooibos-tea/uae',
  path: '/sourcing/rooibos-tea/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingRooibosTeaUnitedStatesRoute =
  SourcingRooibosTeaUnitedStatesRouteImport.update({
    id: '/sourcing/rooibos-tea/united-states',
    path: '/sourcing/rooibos-tea/united-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const SourcingWineAsiaRoute = SourcingWineAsiaRouteImport.update({
  id: '/sourcing/wine/asia',
  path: '/sourcing/wine/asia',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingWineGermanyRoute = SourcingWineGermanyRouteImport.update({
  id: '/sourcing/wine/germany',
  path: '/sourcing/wine/germany',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingWineUaeRoute = SourcingWineUaeRouteImport.update({
  id: '/sourcing/wine/uae',
  path: '/sourcing/wine/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingWineUnitedStatesRoute =
  SourcingWineUnitedStatesRouteImport.update({
    id: '/sourcing/wine/united-states',
    path: '/sourcing/wine/united-states',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/dried-fruit-buyers-guide': typeof GuidesDriedFruitBuyersGuideRoute
  '/guides/macadamia-grades-guide': typeof GuidesMacadamiaGradesGuideRoute
  '/guides/rooibos-tea-guide': typeof GuidesRooibosTeaGuideRoute
  '/guides/south-african-apple-season': typeof GuidesSouthAfricanAppleSeasonRoute
  '/guides/south-african-wine-buyers-guide': typeof GuidesSouthAfricanWineBuyersGuideRoute
  '/products/dried-fruit': typeof ProductsDriedFruitRoute
  '/products/fresh-apples': typeof ProductsFreshApplesRoute
  '/products/nuts': typeof ProductsNutsRoute
  '/products/rooibos-and-tea': typeof ProductsRooibosAndTeaRoute
  '/products/wine': typeof ProductsWineRoute
  '/services/export-coordination': typeof ServicesExportCoordinationRoute
  '/services/supplier-sourcing': typeof ServicesSupplierSourcingRoute
  '/sourcing/dried-fruit/asia': typeof SourcingDriedFruitAsiaRoute
  '/sourcing/dried-fruit/germany': typeof SourcingDriedFruitGermanyRoute
  '/sourcing/dried-fruit/uae': typeof SourcingDriedFruitUaeRoute
  '/sourcing/dried-fruit/united-states': typeof SourcingDriedFruitUnitedStatesRoute
  '/sourcing/fresh-apples/asia': typeof SourcingFreshApplesAsiaRoute
  '/sourcing/fresh-apples/germany': typeof SourcingFreshApplesGermanyRoute
  '/sourcing/fresh-apples/uae': typeof SourcingFreshApplesUaeRoute
  '/sourcing/fresh-apples/united-states': typeof SourcingFreshApplesUnitedStatesRoute
  '/sourcing/macadamia-nuts/asia': typeof SourcingMacadamiaNutsAsiaRoute
  '/sourcing/macadamia-nuts/germany': typeof SourcingMacadamiaNutsGermanyRoute
  '/sourcing/macadamia-nuts/uae': typeof SourcingMacadamiaNutsUaeRoute
  '/sourcing/macadamia-nuts/united-states': typeof SourcingMacadamiaNutsUnitedStatesRoute
  '/sourcing/rooibos-tea/asia': typeof SourcingRooibosTeaAsiaRoute
  '/sourcing/rooibos-tea/germany': typeof SourcingRooibosTeaGermanyRoute
  '/sourcing/rooibos-tea/uae': typeof SourcingRooibosTeaUaeRoute
  '/sourcing/rooibos-tea/united-states': typeof SourcingRooibosTeaUnitedStatesRoute
  '/sourcing/wine/asia': typeof SourcingWineAsiaRoute
  '/sourcing/wine/germany': typeof SourcingWineGermanyRoute
  '/sourcing/wine/uae': typeof SourcingWineUaeRoute
  '/sourcing/wine/united-states': typeof SourcingWineUnitedStatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/dried-fruit-buyers-guide': typeof GuidesDriedFruitBuyersGuideRoute
  '/guides/macadamia-grades-guide': typeof GuidesMacadamiaGradesGuideRoute
  '/guides/rooibos-tea-guide': typeof GuidesRooibosTeaGuideRoute
  '/guides/south-african-apple-season': typeof GuidesSouthAfricanAppleSeasonRoute
  '/guides/south-african-wine-buyers-guide': typeof GuidesSouthAfricanWineBuyersGuideRoute
  '/products/dried-fruit': typeof ProductsDriedFruitRoute
  '/products/fresh-apples': typeof ProductsFreshApplesRoute
  '/products/nuts': typeof ProductsNutsRoute
  '/products/rooibos-and-tea': typeof ProductsRooibosAndTeaRoute
  '/products/wine': typeof ProductsWineRoute
  '/services/export-coordination': typeof ServicesExportCoordinationRoute
  '/services/supplier-sourcing': typeof ServicesSupplierSourcingRoute
  '/sourcing/dried-fruit/asia': typeof SourcingDriedFruitAsiaRoute
  '/sourcing/dried-fruit/germany': typeof SourcingDriedFruitGermanyRoute
  '/sourcing/dried-fruit/uae': typeof SourcingDriedFruitUaeRoute
  '/sourcing/dried-fruit/united-states': typeof SourcingDriedFruitUnitedStatesRoute
  '/sourcing/fresh-apples/asia': typeof SourcingFreshApplesAsiaRoute
  '/sourcing/fresh-apples/germany': typeof SourcingFreshApplesGermanyRoute
  '/sourcing/fresh-apples/uae': typeof SourcingFreshApplesUaeRoute
  '/sourcing/fresh-apples/united-states': typeof SourcingFreshApplesUnitedStatesRoute
  '/sourcing/macadamia-nuts/asia': typeof SourcingMacadamiaNutsAsiaRoute
  '/sourcing/macadamia-nuts/germany': typeof SourcingMacadamiaNutsGermanyRoute
  '/sourcing/macadamia-nuts/uae': typeof SourcingMacadamiaNutsUaeRoute
  '/sourcing/macadamia-nuts/united-states': typeof SourcingMacadamiaNutsUnitedStatesRoute
  '/sourcing/rooibos-tea/asia': typeof SourcingRooibosTeaAsiaRoute
  '/sourcing/rooibos-tea/germany': typeof SourcingRooibosTeaGermanyRoute
  '/sourcing/rooibos-tea/uae': typeof SourcingRooibosTeaUaeRoute
  '/sourcing/rooibos-tea/united-states': typeof SourcingRooibosTeaUnitedStatesRoute
  '/sourcing/wine/asia': typeof SourcingWineAsiaRoute
  '/sourcing/wine/germany': typeof SourcingWineGermanyRoute
  '/sourcing/wine/uae': typeof SourcingWineUaeRoute
  '/sourcing/wine/united-states': typeof SourcingWineUnitedStatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/dried-fruit-buyers-guide': typeof GuidesDriedFruitBuyersGuideRoute
  '/guides/macadamia-grades-guide': typeof GuidesMacadamiaGradesGuideRoute
  '/guides/rooibos-tea-guide': typeof GuidesRooibosTeaGuideRoute
  '/guides/south-african-apple-season': typeof GuidesSouthAfricanAppleSeasonRoute
  '/guides/south-african-wine-buyers-guide': typeof GuidesSouthAfricanWineBuyersGuideRoute
  '/products/dried-fruit': typeof ProductsDriedFruitRoute
  '/products/fresh-apples': typeof ProductsFreshApplesRoute
  '/products/nuts': typeof ProductsNutsRoute
  '/products/rooibos-and-tea': typeof ProductsRooibosAndTeaRoute
  '/products/wine': typeof ProductsWineRoute
  '/services/export-coordination': typeof ServicesExportCoordinationRoute
  '/services/supplier-sourcing': typeof ServicesSupplierSourcingRoute
  '/sourcing/dried-fruit/asia': typeof SourcingDriedFruitAsiaRoute
  '/sourcing/dried-fruit/germany': typeof SourcingDriedFruitGermanyRoute
  '/sourcing/dried-fruit/uae': typeof SourcingDriedFruitUaeRoute
  '/sourcing/dried-fruit/united-states': typeof SourcingDriedFruitUnitedStatesRoute
  '/sourcing/fresh-apples/asia': typeof SourcingFreshApplesAsiaRoute
  '/sourcing/fresh-apples/germany': typeof SourcingFreshApplesGermanyRoute
  '/sourcing/fresh-apples/uae': typeof SourcingFreshApplesUaeRoute
  '/sourcing/fresh-apples/united-states': typeof SourcingFreshApplesUnitedStatesRoute
  '/sourcing/macadamia-nuts/asia': typeof SourcingMacadamiaNutsAsiaRoute
  '/sourcing/macadamia-nuts/germany': typeof SourcingMacadamiaNutsGermanyRoute
  '/sourcing/macadamia-nuts/uae': typeof SourcingMacadamiaNutsUaeRoute
  '/sourcing/macadamia-nuts/united-states': typeof SourcingMacadamiaNutsUnitedStatesRoute
  '/sourcing/rooibos-tea/asia': typeof SourcingRooibosTeaAsiaRoute
  '/sourcing/rooibos-tea/germany': typeof SourcingRooibosTeaGermanyRoute
  '/sourcing/rooibos-tea/uae': typeof SourcingRooibosTeaUaeRoute
  '/sourcing/rooibos-tea/united-states': typeof SourcingRooibosTeaUnitedStatesRoute
  '/sourcing/wine/asia': typeof SourcingWineAsiaRoute
  '/sourcing/wine/germany': typeof SourcingWineGermanyRoute
  '/sourcing/wine/uae': typeof SourcingWineUaeRoute
  '/sourcing/wine/united-states': typeof SourcingWineUnitedStatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/guides/dried-fruit-buyers-guide'
    | '/guides/macadamia-grades-guide'
    | '/guides/rooibos-tea-guide'
    | '/guides/south-african-apple-season'
    | '/guides/south-african-wine-buyers-guide'
    | '/products/dried-fruit'
    | '/products/fresh-apples'
    | '/products/nuts'
    | '/products/rooibos-and-tea'
    | '/products/wine'
    | '/services/export-coordination'
    | '/services/supplier-sourcing'
    | '/sourcing/dried-fruit/asia'
    | '/sourcing/dried-fruit/germany'
    | '/sourcing/dried-fruit/uae'
    | '/sourcing/dried-fruit/united-states'
    | '/sourcing/fresh-apples/asia'
    | '/sourcing/fresh-apples/germany'
    | '/sourcing/fresh-apples/uae'
    | '/sourcing/fresh-apples/united-states'
    | '/sourcing/macadamia-nuts/asia'
    | '/sourcing/macadamia-nuts/germany'
    | '/sourcing/macadamia-nuts/uae'
    | '/sourcing/macadamia-nuts/united-states'
    | '/sourcing/rooibos-tea/asia'
    | '/sourcing/rooibos-tea/germany'
    | '/sourcing/rooibos-tea/uae'
    | '/sourcing/rooibos-tea/united-states'
    | '/sourcing/wine/asia'
    | '/sourcing/wine/germany'
    | '/sourcing/wine/uae'
    | '/sourcing/wine/united-states'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/guides/dried-fruit-buyers-guide'
    | '/guides/macadamia-grades-guide'
    | '/guides/rooibos-tea-guide'
    | '/guides/south-african-apple-season'
    | '/guides/south-african-wine-buyers-guide'
    | '/products/dried-fruit'
    | '/products/fresh-apples'
    | '/products/nuts'
    | '/products/rooibos-and-tea'
    | '/products/wine'
    | '/services/export-coordination'
    | '/services/supplier-sourcing'
    | '/sourcing/dried-fruit/asia'
    | '/sourcing/dried-fruit/germany'
    | '/sourcing/dried-fruit/uae'
    | '/sourcing/dried-fruit/united-states'
    | '/sourcing/fresh-apples/asia'
    | '/sourcing/fresh-apples/germany'
    | '/sourcing/fresh-apples/uae'
    | '/sourcing/fresh-apples/united-states'
    | '/sourcing/macadamia-nuts/asia'
    | '/sourcing/macadamia-nuts/germany'
    | '/sourcing/macadamia-nuts/uae'
    | '/sourcing/macadamia-nuts/united-states'
    | '/sourcing/rooibos-tea/asia'
    | '/sourcing/rooibos-tea/germany'
    | '/sourcing/rooibos-tea/uae'
    | '/sourcing/rooibos-tea/united-states'
    | '/sourcing/wine/asia'
    | '/sourcing/wine/germany'
    | '/sourcing/wine/uae'
    | '/sourcing/wine/united-states'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/guides/dried-fruit-buyers-guide'
    | '/guides/macadamia-grades-guide'
    | '/guides/rooibos-tea-guide'
    | '/guides/south-african-apple-season'
    | '/guides/south-african-wine-buyers-guide'
    | '/products/dried-fruit'
    | '/products/fresh-apples'
    | '/products/nuts'
    | '/products/rooibos-and-tea'
    | '/products/wine'
    | '/services/export-coordination'
    | '/services/supplier-sourcing'
    | '/sourcing/dried-fruit/asia'
    | '/sourcing/dried-fruit/germany'
    | '/sourcing/dried-fruit/uae'
    | '/sourcing/dried-fruit/united-states'
    | '/sourcing/fresh-apples/asia'
    | '/sourcing/fresh-apples/germany'
    | '/sourcing/fresh-apples/uae'
    | '/sourcing/fresh-apples/united-states'
    | '/sourcing/macadamia-nuts/asia'
    | '/sourcing/macadamia-nuts/germany'
    | '/sourcing/macadamia-nuts/uae'
    | '/sourcing/macadamia-nuts/united-states'
    | '/sourcing/rooibos-tea/asia'
    | '/sourcing/rooibos-tea/germany'
    | '/sourcing/rooibos-tea/uae'
    | '/sourcing/rooibos-tea/united-states'
    | '/sourcing/wine/asia'
    | '/sourcing/wine/germany'
    | '/sourcing/wine/uae'
    | '/sourcing/wine/united-states'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesDriedFruitBuyersGuideRoute: typeof GuidesDriedFruitBuyersGuideRoute
  GuidesMacadamiaGradesGuideRoute: typeof GuidesMacadamiaGradesGuideRoute
  GuidesRooibosTeaGuideRoute: typeof GuidesRooibosTeaGuideRoute
  GuidesSouthAfricanAppleSeasonRoute: typeof GuidesSouthAfricanAppleSeasonRoute
  GuidesSouthAfricanWineBuyersGuideRoute: typeof GuidesSouthAfricanWineBuyersGuideRoute
  ProductsDriedFruitRoute: typeof ProductsDriedFruitRoute
  ProductsFreshApplesRoute: typeof ProductsFreshApplesRoute
  ProductsNutsRoute: typeof ProductsNutsRoute
  ProductsRooibosAndTeaRoute: typeof ProductsRooibosAndTeaRoute
  ProductsWineRoute: typeof ProductsWineRoute
  ServicesExportCoordinationRoute: typeof ServicesExportCoordinationRoute
  ServicesSupplierSourcingRoute: typeof ServicesSupplierSourcingRoute
  SourcingDriedFruitAsiaRoute: typeof SourcingDriedFruitAsiaRoute
  SourcingDriedFruitGermanyRoute: typeof SourcingDriedFruitGermanyRoute
  SourcingDriedFruitUaeRoute: typeof SourcingDriedFruitUaeRoute
  SourcingDriedFruitUnitedStatesRoute: typeof SourcingDriedFruitUnitedStatesRoute
  SourcingFreshApplesAsiaRoute: typeof SourcingFreshApplesAsiaRoute
  SourcingFreshApplesGermanyRoute: typeof SourcingFreshApplesGermanyRoute
  SourcingFreshApplesUaeRoute: typeof SourcingFreshApplesUaeRoute
  SourcingFreshApplesUnitedStatesRoute: typeof SourcingFreshApplesUnitedStatesRoute
  SourcingMacadamiaNutsAsiaRoute: typeof SourcingMacadamiaNutsAsiaRoute
  SourcingMacadamiaNutsGermanyRoute: typeof SourcingMacadamiaNutsGermanyRoute
  SourcingMacadamiaNutsUaeRoute: typeof SourcingMacadamiaNutsUaeRoute
  SourcingMacadamiaNutsUnitedStatesRoute: typeof SourcingMacadamiaNutsUnitedStatesRoute
  SourcingRooibosTeaAsiaRoute: typeof SourcingRooibosTeaAsiaRoute
  SourcingRooibosTeaGermanyRoute: typeof SourcingRooibosTeaGermanyRoute
  SourcingRooibosTeaUaeRoute: typeof SourcingRooibosTeaUaeRoute
  SourcingRooibosTeaUnitedStatesRoute: typeof SourcingRooibosTeaUnitedStatesRoute
  SourcingWineAsiaRoute: typeof SourcingWineAsiaRoute
  SourcingWineGermanyRoute: typeof SourcingWineGermanyRoute
  SourcingWineUaeRoute: typeof SourcingWineUaeRoute
  SourcingWineUnitedStatesRoute: typeof SourcingWineUnitedStatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/dried-fruit-buyers-guide': {
      id: '/guides/dried-fruit-buyers-guide'
      path: '/guides/dried-fruit-buyers-guide'
      fullPath: '/guides/dried-fruit-buyers-guide'
      preLoaderRoute: typeof GuidesDriedFruitBuyersGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/macadamia-grades-guide': {
      id: '/guides/macadamia-grades-guide'
      path: '/guides/macadamia-grades-guide'
      fullPath: '/guides/macadamia-grades-guide'
      preLoaderRoute: typeof GuidesMacadamiaGradesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/rooibos-tea-guide': {
      id: '/guides/rooibos-tea-guide'
      path: '/guides/rooibos-tea-guide'
      fullPath: '/guides/rooibos-tea-guide'
      preLoaderRoute: typeof GuidesRooibosTeaGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/south-african-apple-season': {
      id: '/guides/south-african-apple-season'
      path: '/guides/south-african-apple-season'
      fullPath: '/guides/south-african-apple-season'
      preLoaderRoute: typeof GuidesSouthAfricanAppleSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/south-african-wine-buyers-guide': {
      id: '/guides/south-african-wine-buyers-guide'
      path: '/guides/south-african-wine-buyers-guide'
      fullPath: '/guides/south-african-wine-buyers-guide'
      preLoaderRoute: typeof GuidesSouthAfricanWineBuyersGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/dried-fruit': {
      id: '/products/dried-fruit'
      path: '/products/dried-fruit'
      fullPath: '/products/dried-fruit'
      preLoaderRoute: typeof ProductsDriedFruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fresh-apples': {
      id: '/products/fresh-apples'
      path: '/products/fresh-apples'
      fullPath: '/products/fresh-apples'
      preLoaderRoute: typeof ProductsFreshApplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/nuts': {
      id: '/products/nuts'
      path: '/products/nuts'
      fullPath: '/products/nuts'
      preLoaderRoute: typeof ProductsNutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/rooibos-and-tea': {
      id: '/products/rooibos-and-tea'
      path: '/products/rooibos-and-tea'
      fullPath: '/products/rooibos-and-tea'
      preLoaderRoute: typeof ProductsRooibosAndTeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/wine': {
      id: '/products/wine'
      path: '/products/wine'
      fullPath: '/products/wine'
      preLoaderRoute: typeof ProductsWineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/export-coordination': {
      id: '/services/export-coordination'
      path: '/services/export-coordination'
      fullPath: '/services/export-coordination'
      preLoaderRoute: typeof ServicesExportCoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/supplier-sourcing': {
      id: '/services/supplier-sourcing'
      path: '/services/supplier-sourcing'
      fullPath: '/services/supplier-sourcing'
      preLoaderRoute: typeof ServicesSupplierSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/dried-fruit/asia': {
      id: '/sourcing/dried-fruit/asia'
      path: '/sourcing/dried-fruit/asia'
      fullPath: '/sourcing/dried-fruit/asia'
      preLoaderRoute: typeof SourcingDriedFruitAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/dried-fruit/germany': {
      id: '/sourcing/dried-fruit/germany'
      path: '/sourcing/dried-fruit/germany'
      fullPath: '/sourcing/dried-fruit/germany'
      preLoaderRoute: typeof SourcingDriedFruitGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/dried-fruit/uae': {
      id: '/sourcing/dried-fruit/uae'
      path: '/sourcing/dried-fruit/uae'
      fullPath: '/sourcing/dried-fruit/uae'
      preLoaderRoute: typeof SourcingDriedFruitUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/dried-fruit/united-states': {
      id: '/sourcing/dried-fruit/united-states'
      path: '/sourcing/dried-fruit/united-states'
      fullPath: '/sourcing/dried-fruit/united-states'
      preLoaderRoute: typeof SourcingDriedFruitUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/fresh-apples/asia': {
      id: '/sourcing/fresh-apples/asia'
      path: '/sourcing/fresh-apples/asia'
      fullPath: '/sourcing/fresh-apples/asia'
      preLoaderRoute: typeof SourcingFreshApplesAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/fresh-apples/germany': {
      id: '/sourcing/fresh-apples/germany'
      path: '/sourcing/fresh-apples/germany'
      fullPath: '/sourcing/fresh-apples/germany'
      preLoaderRoute: typeof SourcingFreshApplesGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/fresh-apples/uae': {
      id: '/sourcing/fresh-apples/uae'
      path: '/sourcing/fresh-apples/uae'
      fullPath: '/sourcing/fresh-apples/uae'
      preLoaderRoute: typeof SourcingFreshApplesUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/fresh-apples/united-states': {
      id: '/sourcing/fresh-apples/united-states'
      path: '/sourcing/fresh-apples/united-states'
      fullPath: '/sourcing/fresh-apples/united-states'
      preLoaderRoute: typeof SourcingFreshApplesUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/macadamia-nuts/asia': {
      id: '/sourcing/macadamia-nuts/asia'
      path: '/sourcing/macadamia-nuts/asia'
      fullPath: '/sourcing/macadamia-nuts/asia'
      preLoaderRoute: typeof SourcingMacadamiaNutsAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/macadamia-nuts/germany': {
      id: '/sourcing/macadamia-nuts/germany'
      path: '/sourcing/macadamia-nuts/germany'
      fullPath: '/sourcing/macadamia-nuts/germany'
      preLoaderRoute: typeof SourcingMacadamiaNutsGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/macadamia-nuts/uae': {
      id: '/sourcing/macadamia-nuts/uae'
      path: '/sourcing/macadamia-nuts/uae'
      fullPath: '/sourcing/macadamia-nuts/uae'
      preLoaderRoute: typeof SourcingMacadamiaNutsUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/macadamia-nuts/united-states': {
      id: '/sourcing/macadamia-nuts/united-states'
      path: '/sourcing/macadamia-nuts/united-states'
      fullPath: '/sourcing/macadamia-nuts/united-states'
      preLoaderRoute: typeof SourcingMacadamiaNutsUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/rooibos-tea/asia': {
      id: '/sourcing/rooibos-tea/asia'
      path: '/sourcing/rooibos-tea/asia'
      fullPath: '/sourcing/rooibos-tea/asia'
      preLoaderRoute: typeof SourcingRooibosTeaAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/rooibos-tea/germany': {
      id: '/sourcing/rooibos-tea/germany'
      path: '/sourcing/rooibos-tea/germany'
      fullPath: '/sourcing/rooibos-tea/germany'
      preLoaderRoute: typeof SourcingRooibosTeaGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/rooibos-tea/uae': {
      id: '/sourcing/rooibos-tea/uae'
      path: '/sourcing/rooibos-tea/uae'
      fullPath: '/sourcing/rooibos-tea/uae'
      preLoaderRoute: typeof SourcingRooibosTeaUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/rooibos-tea/united-states': {
      id: '/sourcing/rooibos-tea/united-states'
      path: '/sourcing/rooibos-tea/united-states'
      fullPath: '/sourcing/rooibos-tea/united-states'
      preLoaderRoute: typeof SourcingRooibosTeaUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/wine/asia': {
      id: '/sourcing/wine/asia'
      path: '/sourcing/wine/asia'
      fullPath: '/sourcing/wine/asia'
      preLoaderRoute: typeof SourcingWineAsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/wine/germany': {
      id: '/sourcing/wine/germany'
      path: '/sourcing/wine/germany'
      fullPath: '/sourcing/wine/germany'
      preLoaderRoute: typeof SourcingWineGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/wine/uae': {
      id: '/sourcing/wine/uae'
      path: '/sourcing/wine/uae'
      fullPath: '/sourcing/wine/uae'
      preLoaderRoute: typeof SourcingWineUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/wine/united-states': {
      id: '/sourcing/wine/united-states'
      path: '/sourcing/wine/united-states'
      fullPath: '/sourcing/wine/united-states'
      preLoaderRoute: typeof SourcingWineUnitedStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesDriedFruitBuyersGuideRoute: GuidesDriedFruitBuyersGuideRoute,
  GuidesMacadamiaGradesGuideRoute: GuidesMacadamiaGradesGuideRoute,
  GuidesRooibosTeaGuideRoute: GuidesRooibosTeaGuideRoute,
  GuidesSouthAfricanAppleSeasonRoute: GuidesSouthAfricanAppleSeasonRoute,
  GuidesSouthAfricanWineBuyersGuideRoute:
    GuidesSouthAfricanWineBuyersGuideRoute,
  ProductsDriedFruitRoute: ProductsDriedFruitRoute,
  ProductsFreshApplesRoute: ProductsFreshApplesRoute,
  ProductsNutsRoute: ProductsNutsRoute,
  ProductsRooibosAndTeaRoute: ProductsRooibosAndTeaRoute,
  ProductsWineRoute: ProductsWineRoute,
  ServicesExportCoordinationRoute: ServicesExportCoordinationRoute,
  ServicesSupplierSourcingRoute: ServicesSupplierSourcingRoute,
  SourcingDriedFruitAsiaRoute: SourcingDriedFruitAsiaRoute,
  SourcingDriedFruitGermanyRoute: SourcingDriedFruitGermanyRoute,
  SourcingDriedFruitUaeRoute: SourcingDriedFruitUaeRoute,
  SourcingDriedFruitUnitedStatesRoute: SourcingDriedFruitUnitedStatesRoute,
  SourcingFreshApplesAsiaRoute: SourcingFreshApplesAsiaRoute,
  SourcingFreshApplesGermanyRoute: SourcingFreshApplesGermanyRoute,
  SourcingFreshApplesUaeRoute: SourcingFreshApplesUaeRoute,
  SourcingFreshApplesUnitedStatesRoute: SourcingFreshApplesUnitedStatesRoute,
  SourcingMacadamiaNutsAsiaRoute: SourcingMacadamiaNutsAsiaRoute,
  SourcingMacadamiaNutsGermanyRoute: SourcingMacadamiaNutsGermanyRoute,
  SourcingMacadamiaNutsUaeRoute: SourcingMacadamiaNutsUaeRoute,
  SourcingMacadamiaNutsUnitedStatesRoute:
    SourcingMacadamiaNutsUnitedStatesRoute,
  SourcingRooibosTeaAsiaRoute: SourcingRooibosTeaAsiaRoute,
  SourcingRooibosTeaGermanyRoute: SourcingRooibosTeaGermanyRoute,
  SourcingRooibosTeaUaeRoute: SourcingRooibosTeaUaeRoute,
  SourcingRooibosTeaUnitedStatesRoute: SourcingRooibosTeaUnitedStatesRoute,
  SourcingWineAsiaRoute: SourcingWineAsiaRoute,
  SourcingWineGermanyRoute: SourcingWineGermanyRoute,
  SourcingWineUaeRoute: SourcingWineUaeRoute,
  SourcingWineUnitedStatesRoute: SourcingWineUnitedStatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
